### ISSUE TITLE
Can not detach instance from LB that has multiple instances attached

### ISSUE THREAD

**Issue by harikiriboy** [nifcloud/ansible-role-nifcloud#24]
# Summary

I find bug.
 If target LB has multiple instances attached, can not detach instance from LB, because [this if statement](https://github.com/NIFTYCloud/ansible-role-niftycloud/blob/master/library/niftycloud_lb.py#L193) only compares with the first Instance attached to the load balancer

* example 
```
LB
  instance001
  instance002
```
`instance002` can not detach.

**Comment by fuku2014** [comment]
Resolved by #57 🎉
